language: python

python:
  - "3.7"

cache: pip

git:
  depth: 1

install:
  - pip install -r requirements.txt
  - pip install travis-sphinx
  - ./getPBR.sh

stages:
  - prepare cache
  - test

script: ./${TEST_CASE}.sh

jobs:
  include:
    - stage: prepare cache
      script: true
    - stage: test
      env: TEST_CASE=build
      after_success: cd target && travis-sphinx deploy
    - stage: test
      env: TEST_CASE=test
